name: my_app
description: A minimal Flutter project.
dependencies:
  flutter:
    path: "../../git/flutter/packages/flutter"
  syncbase: ">=0.0.15 <0.1.0"
dev_dependencies:
  flutter_tools:
    path: "../../git/flutter/packages/flutter_tools"
